runtime: python39
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  FLASK_ENV: "production"
  SECRET_KEY: "your-secret-key-here"  # Replace with a secure secret key

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.png
  upload: static/img/favicon\.png

- url: /static
  static_dir: static

- url: /.*
  script: auto

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  max_concurrent_requests: 50

instance_class: F1

inbound_services:
- warmup

liveness_check:
  path: "/liveness_check"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300